<a href="https://colab.research.google.com/github/IvanGonzal0/Big-Data-y-ML/blob/main/BigData_C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [37]:
# Como crear un DF a partir de listas o datos creados por nosotros
producto = ['Laptop', 'Telefono', 'Televisor', 'Tablet',  'Camara', 'Smartwatch', 'Auriculares']
precio = [800, 500, 1000, 300, 400, 200, 150]

unidad_vendidas = [50, 120, 80, 30, 65, 70, 40]

total_ventas = [40000, 60000, 80000, 9000, 180000, 18000, 6000]

df = pd.DataFrame({'Producto' : producto,
                   'Precio' : precio,
                   'Unidades' : unidad_vendidas,
                   'Ventas' : total_ventas})
df

      Producto  Precio  Unidades  Ventas
0       Laptop     800        50   40000
1     Telefono     500       120   60000
2    Televisor    1000        80   80000
3       Tablet     300        30    9000
4       Camara     400        65  180000
5   Smartwatch     200        70   18000
6  Auriculares     150        40    6000

In [38]:
# Descripción general del ds
df.describe()

            Precio    Unidades         Ventas
count     7.000000    7.000000       7.000000
mean    478.571429   65.000000   56142.857143
std     316.039479   29.860788   61069.437450
min     150.000000   30.000000    6000.000000
25%     250.000000   45.000000   13500.000000
50%     400.000000   65.000000   40000.000000
75%     650.000000   75.000000   70000.000000
max    1000.000000  120.000000  180000.000000

In [39]:
# tail me muestro los ultimos y df head me muestra los primeros
df.tail()
df.head()

    Producto  Precio  Unidades  Ventas
0     Laptop     800        50   40000
1   Telefono     500       120   60000
2  Televisor    1000        80   80000
3     Tablet     300        30    9000
4     Camara     400        65  180000

In [40]:
# Para trabajar una columna (una serie)
df['Precio']

0     800
1     500
2    1000
3     300
4     400
5     200
6     150
Name: Precio, dtype: int64

In [41]:
# loc me sirve para filtrar/ seleccionar datos de columnas especificas creando un nuevo df

df_filtrado = df.loc[:,['Producto']]
df_filtrado

      Producto
0       Laptop
1     Telefono
2    Televisor
3       Tablet
4       Camara
5   Smartwatch
6  Auriculares

In [42]:
# loc el primer parametro son los datos especificos que necesito, y el segundo parametro son las columnas o el df que necesito

df_filtrado = df.loc[2:4,['Producto', 'Unidades']]
df_filtrado

    Producto  Unidades
2  Televisor        80
3     Tablet        30
4     Camara        65

In [43]:
# Para seleccionar un solo producto podemos tambien utilizar loc

df_producto_solo = df.loc[0]
df_producto_solo

Producto    Laptop
Precio         800
Unidades        50
Ventas       40000
Name: 0, dtype: object

In [44]:
# Para seleccionar todo
df_filtrado = df.loc[:]
df_filtrado

      Producto  Precio  Unidades  Ventas
0       Laptop     800        50   40000
1     Telefono     500       120   60000
2    Televisor    1000        80   80000
3       Tablet     300        30    9000
4       Camara     400        65  180000
5   Smartwatch     200        70   18000
6  Auriculares     150        40    6000

In [45]:
# Creación de una nueva columna
df['Ventas Totales en $'] = df['Precio']*df['Unidades']
df

      Producto  Precio  Unidades  Ventas  Ventas Totales en $
0       Laptop     800        50   40000                40000
1     Telefono     500       120   60000                60000
2    Televisor    1000        80   80000                80000
3       Tablet     300        30    9000                 9000
4       Camara     400        65  180000                26000
5   Smartwatch     200        70   18000                14000
6  Auriculares     150        40    6000                 6000

In [46]:
# Otra forma de crear un df
producto = ['Monitor', 'Procesador', 'Disco duro', 'Tarjeta grafica',  'RAM']

precio = [800, 500, 1000, 300, 400 ]

precio = [70,200,100,50,35]

unidades_vendidas = [400,150,800,25,100]

data = {
    'Producto':producto,
    'Precio':precio,
    'Unidades':unidades_vendidas
}

df2 = pd.DataFrame(data)
df2.head()

          Producto  Precio  Unidades
0          Monitor      70       400
1       Procesador     200       150
2       Disco duro     100       800
3  Tarjeta grafica      50        25
4              RAM      35       100

In [47]:
# Creamos una nueva columna
df2['Ventas Totales en $'] = df['Precio']*df['Unidades']
df2

          Producto  Precio  Unidades  Ventas Totales en $
0          Monitor      70       400                40000
1       Procesador     200       150                60000
2       Disco duro     100       800                80000
3  Tarjeta grafica      50        25                 9000
4              RAM      35       100                26000

In [48]:
# Podemos concatenar 2 df que tengan relacion
df_concatenado = pd.concat([df, df2], ignore_index = True)
df_concatenado

           Producto  Precio  Unidades    Ventas  Ventas Totales en $
0            Laptop     800        50   40000.0                40000
1          Telefono     500       120   60000.0                60000
2         Televisor    1000        80   80000.0                80000
3            Tablet     300        30    9000.0                 9000
4            Camara     400        65  180000.0                26000
5        Smartwatch     200        70   18000.0                14000
6       Auriculares     150        40    6000.0                 6000
7           Monitor      70       400       NaN                40000
8        Procesador     200       150       NaN                60000
9        Disco duro     100       800       NaN                80000
10  Tarjeta grafica      50        25       NaN                 9000
11              RAM      35       100       NaN                26000

In [55]:
# Eliminar una columna
df.drop('Ventas', axis=1, inplace=True)
df

      Producto  Precio  Unidades  Ventas Totales en $
0       Laptop     800        50                40000
1     Telefono     500       120                60000
2    Televisor    1000        80                80000
3       Tablet     300        30                 9000
4       Camara     400        65                26000
5   Smartwatch     200        70                14000
6  Auriculares     150        40                 6000

In [56]:
# Filtrar por valores altos

df_alto_valor = df.loc[df['Unidades']>40]

df_alto_valor

     Producto  Precio  Unidades  Ventas Totales en $
0      Laptop     800        50                40000
1    Telefono     500       120                60000
2   Televisor    1000        80                80000
4      Camara     400        65                26000
5  Smartwatch     200        70                14000

In [57]:
# Seleccionar productos especificos por nombre

productos_seleccionados = ['Procesador', 'RAM' , 'Monitor', 'Tarjeta grafica']

In [58]:
# Esto selecciona ciertos productos y me devulve un array de booleanos

prod_seleccionados = df_concatenado['Producto'].isin(productos_seleccionados)
prod_seleccionados

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9     False
10     True
11     True
Name: Producto, dtype: bool

In [59]:
# Para obtener los datos en un df y no solo los booleanos

df_prod_seleccionados = df_concatenado[df_concatenado['Producto'].isin(productos_seleccionados)]
df_prod_seleccionados

           Producto  Precio  Unidades  Ventas Totales en $
7           Monitor      70       400                40000
8        Procesador     200       150                60000
10  Tarjeta grafica      50        25                 9000
11              RAM      35       100                26000

In [62]:
# Promedios  de una columna

promedio_unidades = df_concatenado['Unidades'].mean()

promedio_unidades

160.83333333333334

In [63]:
# Suma de valores

suma_unidades = df_concatenado['Unidades'].sum()

suma_unidades

1930

In [64]:
# Minimo de la columna

min_unidades = df_concatenado['Unidades'].min()

min_unidades

25

In [65]:
# IMPORTANDO CSV

path = '/content/Dataset_de_ventas_Abril.csv'

df_ventas = pd.read_csv(path)

df_ventas

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [66]:
df_ventas.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"

In [69]:
# Limpiar el dataset de valores NaN

df_ventas = df_ventas.dropna()
df_ventas.head(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"
7,176563,Bose SoundSport Headphones,1,99.99,04/02/19 07:46,"668 Center St, Seattle, WA 98101"
8,176564,USB-C Charging Cable,1,11.95,04/12/19 10:58,"790 Ridge St, Atlanta, GA 30301"
9,176565,Macbook Pro Laptop,1,1700,04/24/19 10:38,"915 Willow St, San Francisco, CA 94016"
10,176566,Wired Headphones,1,11.99,04/08/19 14:05,"83 7th St, Boston, MA 02215"

In [71]:
# Limpiar NaN reemplazando todos los Nan por 0

df_ventas = df_ventas.fillna(0)
df_ventas

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
# Otra forma de manipular los NaN
df_ventas = df_ventas.fillna({'Quantity Ordered' : 0, 'Price Each':2})
df_ventas

In [72]:
# Otra vez para sacar los NaN definitivamente (es lo mas comun)

df_ventas = df_ventas.dropna()
df_ventas

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [74]:
# Como reemplazar DATOS que no sean numericos a NaN (por que esten mal cargados), con el errors= 'coerce' transformo todos esos datos que no sean numeros en NaN
# Aca todos los valores de quantity order y price each pasamelos a NaN para luego limpiar el df de nuevo
# Esto me sirve para poder analizar sin problemas y sin errores (LIMPIEZA)

df_ventas['Quantity Ordered'] = pd.to_numeric(df_ventas['Quantity Ordered'] ,errors = 'coerce')
df_ventas['Price Each'] = pd.to_numeric(df_ventas['Price Each'] ,errors = 'coerce')

df_ventas.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2.0,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1.0,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1.0,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1.0,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1.0,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [75]:
# limpio de nuevo los NaN por caso que hubiera valores que no eran numeros

df_ventas = df_ventas.dropna()
df_ventas.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2.0,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1.0,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1.0,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1.0,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1.0,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [77]:
# Para clonar un df podemos hacer

df_ventas2 = df_ventas.copy()

In [78]:
# LIMPIEZA y manipulacion de tipos de datos

df_ventas['Quantity Ordered'] = pd.to_numeric(df_ventas['Quantity Ordered'] ,errors = 'coerce')
df_ventas['Price Each'] = pd.to_numeric(df_ventas['Price Each'] ,errors = 'coerce')

df_ventas = df_ventas.dropna()

df_ventas['Quantity Ordered'] = df_ventas['Quantity Ordered'].astype(int)
df_ventas['Price Each'] = df_ventas['Price Each'].astype(float)

df_ventas.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600.00,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [81]:
# Filtramos los productos que se pidieron mas de 5 unidades en la misma orden de compra
df_alto_valor = df_ventas.loc[df_ventas['Quantity Ordered']>=5]
df_alto_valor

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
480,177017,AAA Batteries (4-pack),5,2.99,04/16/19 00:04,"713 Sunset St, New York City, NY 10001"
628,177160,AAA Batteries (4-pack),7,2.99,04/26/19 11:37,"689 7th St, Dallas, TX 75001"
1348,177838,AAA Batteries (4-pack),6,2.99,04/29/19 00:16,"872 Pine St, San Francisco, CA 94016"
1590,178071,AA Batteries (4-pack),5,3.84,04/20/19 11:51,"79 1st St, San Francisco, CA 94016"
1746,178217,AAA Batteries (4-pack),5,2.99,04/01/19 10:09,"721 Park St, Los Angeles, CA 90001"
1954,178418,AAA Batteries (4-pack),5,2.99,04/26/19 11:09,"62 Pine St, San Francisco, CA 94016"
2952,179384,AAA Batteries (4-pack),5,2.99,04/21/19 05:05,"903 Madison St, Atlanta, GA 30301"
3198,179619,AA Batteries (4-pack),5,3.84,04/03/19 10:50,"781 Center St, Portland, OR 97035"
3451,179865,AAA Batteries (4-pack),6,2.99,04/14/19 11:24,"83 Willow St, Austin, TX 73301"
3642,180048,AAA Batteries (4-pack),5,2.99,04/06/19 17:30,"818 1st St, Portland, OR 97035"
3935,180333,AA Batteries (4-pack),5,3.84,04/14/19 09:15,"442 Madison St, Seattle, WA 98101"
5951,182243,AAA Batteries (4-pack),5,2.99,04/24/19 12:03,"142 Washington St, Atlanta, GA 30301"
7422,183636,AAA Batteries (4-pack),6,2.99,04/30/19 10:28,"116 11th St, Boston, MA 02215"
8074,184266,AAA Batteries (4-pack),5,2.99,04/13/19 19:26,"932 Ridge St, San Francisco, CA 94016"
8189,184378,AAA Batteries (4-pack),5,2.99,04/22/19 09:38,"927 Maple St, Atlanta, GA 30301"
9207,185349,AAA Batteries (4-pack),5,2.99,04/26/19 07:26,"675 Center St, Boston, MA 02215"
9587,185711,AA Batteries (4-pack),5,3.84,04/10/19 11:54,"481 South St, Los Angeles, CA 90001"
9658,185776,AAA Batteries (4-pack),6,2.99,04/14/19 21:18,"85 Maple St, San Francisco, CA 94016"
9802,185915,AA Batteries (4-pack),5,3.84,04/14/19 17:15,"749 Sunset St, Los Angeles, CA 90001"
9921,186028,AAA Batteries (4-pack),5,2.99,04/12/19 13:54,"414 Chestnut St, San Francisco, CA 94016"
10238,186331,AAA Batteries (4-pack),5,2.99,04/09/19 11:35,"553 2nd St, Los Angeles, CA 90001"
10937,186997,USB-C Charging Cable,6,11.95,04/23/19 21:54,"733 Chestnut St, Seattle, WA 98101"
11129,187182,AA Batteries (4-pack),5,3.84,04/06/19 13:05,"34 South St, New York City, NY 10001"
11836,187851,AAA Batteries (4-pack),6,2.99,04/12/19 00:09,"350 Wilson St, Boston, MA 02215"
13004,188953,AAA Batteries (4-pack),5,2.99,04/30/19 09:32,"20 Maple St, Los Angeles, CA 90001"
14581,190462,AA Batteries (4-pack),5,3.84,04/04/19 12:28,"273 Jackson St, Portland, OR 97035"
14971,190838,AA Batteries (4-pack),5,3.84,04/13/19 12:59,"787 Main St, Boston, MA 02215"
15414,191260,AAA Batteries (4-pack),6,2.99,04/17/19 15:06,"843 Cedar St, Los Angeles, CA 90001"
15484,191328,AAA Batteries (4-pack),5,2.99,04/12/19 14:34,"503 Park St, Los Angeles, CA 90001"
16323,192130,AAA Batteries (4-pack),5,2.99,04/10/19 22:36,"565 Forest St, San Francisco, CA 94016"
16354,192160,AAA Batteries (4-pack),5,2.99,04/22/19 00:03,"498 Washington St, Atlanta, GA 30301"
17156,192932,AAA Batteries (4-pack),5,2.99,04/08/19 16:51,"553 Dogwood St, Seattle, WA 98101"

In [85]:
# Podemos agrupar los productos
productos_vendidos = df_ventas.groupby('Product')['Quantity Ordered']

productos_vendidos.head()

0       2
2       1
3       1
4       1
5       1
       ..
598     1
613     1
867     1
1422    1
1630    1
Name: Quantity Ordered, Length: 95, dtype: int64

In [87]:
# Podemos agrupar los productos y sumar las cantidades
productos_vendidos = df_ventas.groupby('Product')['Quantity Ordered'].sum()

productos_vendidos.head()

Product
20in Monitor               395
27in 4K Gaming Monitor     565
27in FHD Monitor           737
34in Ultrawide Monitor     653
AA Batteries (4-pack)     2822
Name: Quantity Ordered, dtype: int64

In [89]:
# Podemos agrupar sumar y ordenarlos

productos_vendidos = df_ventas.groupby('Product')['Quantity Ordered'].sum()
productos_vendidos = productos_vendidos.sort_values(ascending = False)
productos_vendidos.head()

Product
AAA Batteries (4-pack)      2936
AA Batteries (4-pack)       2822
Lightning Charging Cable    2371
USB-C Charging Cable        2270
Wired Headphones            2066
Name: Quantity Ordered, dtype: int64

In [91]:
# Analisis de productos
# agg es ucnaod quiero hacer multiples operaciones ( se usa un diccionario y se le pasa una clave valor con columna : funcion a realizar)
analisis_de_productos = df_ventas.groupby('Product').agg({
    'Quantity Ordered':'sum',
    'Price Each': 'mean'
})

analisis_de_productos = analisis_de_productos.sort_values(by ='Quantity Ordered', ascending = False)

analisis_de_productos

                            Quantity Ordered  Price Each
Product
AAA Batteries (4-pack)                  2936        2.99
AA Batteries (4-pack)                   2822        3.84
Lightning Charging Cable                2371       14.95
USB-C Charging Cable                    2270       11.95
Wired Headphones                        2066       11.99
Apple Airpods Headphones                1525      150.00
Bose SoundSport Headphones              1288       99.99
27in FHD Monitor                         737      149.99
iPhone                                   695      700.00
34in Ultrawide Monitor                   653      379.99
Google Phone                             581      600.00
27in 4K Gaming Monitor                   565      389.99
Flatscreen TV                            459      300.00
Macbook Pro Laptop                       455     1700.00
20in Monitor                             395      109.99
ThinkPad Laptop                          392      999.99
Vareebadd Phone                          220      400.00
LG Dryer                                  77      600.00
LG Washing Machine                        61      600.00

In [92]:
# Aca puedo obtener el total de ventas de todos los productos haciendo la cuenta de la cantidad de productos vendidos por orden * el precio de cada producto
analisis_de_productos['Total Sales'] = analisis_de_productos['Quantity Ordered'] *analisis_de_productos['Price Each']

# obtenemos el promedio de prodcutos*precio
analisis_de_productos

                            Quantity Ordered  Price Each  Total Sales
Product
AAA Batteries (4-pack)                  2936        2.99      8778.64
AA Batteries (4-pack)                   2822        3.84     10836.48
Lightning Charging Cable                2371       14.95     35446.45
USB-C Charging Cable                    2270       11.95     27126.50
Wired Headphones                        2066       11.99     24771.34
Apple Airpods Headphones                1525      150.00    228750.00
Bose SoundSport Headphones              1288       99.99    128787.12
27in FHD Monitor                         737      149.99    110542.63
iPhone                                   695      700.00    486500.00
34in Ultrawide Monitor                   653      379.99    248133.47
Google Phone                             581      600.00    348600.00
27in 4K Gaming Monitor                   565      389.99    220344.35
Flatscreen TV                            459      300.00    137700.00
Macbook Pro Laptop                       455     1700.00    773500.00
20in Monitor                             395      109.99     43446.05
ThinkPad Laptop                          392      999.99    391996.08
Vareebadd Phone                          220      400.00     88000.00
LG Dryer                                  77      600.00     46200.00
LG Washing Machine                        61      600.00     36600.00

In [93]:
#aca lo podemos ordenar por la ganancia genereda. a partir la columna total sales
analisis_de_productos = analisis_de_productos.sort_values(by='Total Sales', ascending = False)
analisis_de_productos

                            Quantity Ordered  Price Each  Total Sales
Product
Macbook Pro Laptop                       455     1700.00    773500.00
iPhone                                   695      700.00    486500.00
ThinkPad Laptop                          392      999.99    391996.08
Google Phone                             581      600.00    348600.00
34in Ultrawide Monitor                   653      379.99    248133.47
Apple Airpods Headphones                1525      150.00    228750.00
27in 4K Gaming Monitor                   565      389.99    220344.35
Flatscreen TV                            459      300.00    137700.00
Bose SoundSport Headphones              1288       99.99    128787.12
27in FHD Monitor                         737      149.99    110542.63
Vareebadd Phone                          220      400.00     88000.00
LG Dryer                                  77      600.00     46200.00
20in Monitor                             395      109.99     43446.05
LG Washing Machine                        61      600.00     36600.00
Lightning Charging Cable                2371       14.95     35446.45
USB-C Charging Cable                    2270       11.95     27126.50
Wired Headphones                        2066       11.99     24771.34
AA Batteries (4-pack)                   2822        3.84     10836.48
AAA Batteries (4-pack)                  2936        2.99      8778.64

In [94]:
# Aca ordeno por la mayor cantidad de productos vendidos
analisis_de_productos = analisis_de_productos.sort_values(by='Quantity Ordered', ascending = False)
analisis_de_productos

                            Quantity Ordered  Price Each  Total Sales
Product
AAA Batteries (4-pack)                  2936        2.99      8778.64
AA Batteries (4-pack)                   2822        3.84     10836.48
Lightning Charging Cable                2371       14.95     35446.45
USB-C Charging Cable                    2270       11.95     27126.50
Wired Headphones                        2066       11.99     24771.34
Apple Airpods Headphones                1525      150.00    228750.00
Bose SoundSport Headphones              1288       99.99    128787.12
27in FHD Monitor                         737      149.99    110542.63
iPhone                                   695      700.00    486500.00
34in Ultrawide Monitor                   653      379.99    248133.47
Google Phone                             581      600.00    348600.00
27in 4K Gaming Monitor                   565      389.99    220344.35
Flatscreen TV                            459      300.00    137700.00
Macbook Pro Laptop                       455     1700.00    773500.00
20in Monitor                             395      109.99     43446.05
ThinkPad Laptop                          392      999.99    391996.08
Vareebadd Phone                          220      400.00     88000.00
LG Dryer                                  77      600.00     46200.00
LG Washing Machine                        61      600.00     36600.00